# Generated by Django 4.1.7 on 2023-03-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
