# Generated by Django 4.1.7 on 2023-04-13 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0003_noteshistory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='UpdationDate',
        ),
        migrations.AddField(
            model_name='notes',
            name='noteDescription',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='noteTitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='signup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enotes.signup'),
        ),
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enotes.category'),
        ),
    ]
