# Generated by Django 4.1.7 on 2023-04-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0004_remove_notes_category_remove_notes_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='UpdationDate',
            field=models.DateField(null=True),
        ),
    ]
