# Generated by Django 4.1.7 on 2023-04-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0005_notes_updationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enotes.notes')),
            ],
        ),
    ]
