# Generated by Django 4.1.7 on 2023-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0006_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
