# Generated by Django 4.1.7 on 2023-04-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0009_tag_remove_notes_tags_notes_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
